### ISSUE TITLE
Why does `DataSize.Unit.KILOBYTE` have `unitString` of `kB` instead of `KB`?

### ISSUE THREAD

**Issue by Genzer** [airlift/units#10]
Hi guys,

We would like to use your library in our project for providing human-friendly input for data size. However, I have noticed an odd thing: The `DataSize.Unit.KILOBYTE` is initialized with `kB` whereas  the others are `MB`, `PB`, etc.

Is it by design? Could you share why you had decided it that way?

Thanks a lot for your time!
Genzer

**Comment by dain** [comment]
We follow the Si unit meaning.  Here is a wikipedia article on it: https://en.wikipedia.org/wiki/Units_of_information#Units_of_information  An applicable quote from the quote:

> In the past, uppercase K has been used instead of lowercase k to indicate 1024 instead of 1000. However, this usage was never consistently applied.

**Comment by Genzer** [comment]
Thanks for your answer! I also came across the wikipedia page.

I'll close this one then.
