### ISSUE TITLE
Make units extensible

### ISSUE THREAD

**Issue by kokosing** [airlift/units#7]
Currently units are not extensible and there are only two of them Duration and DataSize. Sometimes it is needed that have an unit that is only usable in some narrow use case (like CPU cost unit), it would be nice to leverage airlift-units for that.

See https://github.com/prestodb/presto/pull/11443 for reference.

**Comment by dain** [comment]
@kokosing, I'm not sure what you are thinking, but one of the things I like best about units is the type safety we get from not having it be very extensible.  Instead, I propose you create issues for the additional unit systems you need, and we'll just code up those ones.

**Comment by kokosing** [comment]
> I like best about units is the type safety we get

This is something that should remain unchanged. I was thinking about extracting some abstraction from `DataSize`, so `DataSize` and any other similar unit could be built on top of that`. I would like to inject things like the unit (`B` in case of data size), and metric prefixes with their factors (in case of data size: 1024 - k, 1024*1024 - M, ...)

**Comment by kokosing** [comment]
BTW it is related to https://github.com/prestodb/presto/pull/11443, custom unit would help to remove the regex usage and fix comments like https://github.com/prestodb/presto/pull/11443#issuecomment-433927130, until CBO CPU cost change to duration unit.
